In [9]:
import spacy 
import pandas as pd

In [10]:
nlp = spacy.load("en_core_web_sm")

In [11]:
emma_ja = "emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unite some of the best blessings of existence and had lived nearly twentyone years in the world with very little to distress or vex her she was the youngest of the two daughters of a most affectionate indulgent father and had in consequence of her sisters marriage been mistress of his house from a very early period her mother had died too long ago for her to have more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as governess who had fallen little short of a mother in affection sixteen years had miss taylor been in mr woodhouses family less as a governess than a friend very fond of both daughters but particularly of emma between them it was more the intimacy of sisters even before miss taylor had ceased to hold the nominal office of governess the mildness of her temper had hardly allowed her to impose any restraint and the shadow of authority being now long passed away they had been living together as friend and friend very mutually attached and emma doing just what she liked highly esteeming miss taylors judgment but directed chiefly by her own"
print(emma_ja)

emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unite some of the best blessings of existence and had lived nearly twentyone years in the world with very little to distress or vex her she was the youngest of the two daughters of a most affectionate indulgent father and had in consequence of her sisters marriage been mistress of his house from a very early period her mother had died too long ago for her to have more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as governess who had fallen little short of a mother in affection sixteen years had miss taylor been in mr woodhouses family less as a governess than a friend very fond of both daughters but particularly of emma between them it was more the intimacy of sisters even before miss taylor had ceased to hold the nominal office of governess the mildness of her temper had hardly allowed her to impose any restraint and the shadow of authority being now long passed away they had been living together as friend and friend very mutually attached and emma doing just what she liked highly esteeming miss taylors judgment but directed chiefly by her own

In [12]:
spacy_doc= nlp(emma_ja)

In [13]:
pos_df = pd.DataFrame(columns=['token','pos_tag'])

In [14]:
for token in spacy_doc:
    pos_df = pd.concat([pos_df, pd.DataFrame({'token': token.text, 'pos_tag': token.pos_}, index=[0])], ignore_index=True)

In [15]:
pos_df.head(15)

          token pos_tag
0          emma   PROPN
1     woodhouse   PROPN
2      handsome     ADJ
3        clever     ADJ
4           and   CCONJ
5          rich     ADJ
6          with     ADP
7             a     DET
8   comfortable     ADJ
9          home    NOUN
10          and   CCONJ
11        happy     ADJ
12  disposition    NOUN
13       seemed    VERB
14           to    PART

In [16]:
pos_df_counts = pos_df.groupby(['token','pos_tag']).size().reset_index(name='counts').sort_values(by='counts', ascending=False  )
pos_df_counts.head(15)

         token pos_tag  counts
88          of     ADP      14
49         had     AUX       9
54         her    PRON       9
111        the     DET       8
6          and   CCONJ       8
0            a     DET       6
114         to    PART       5
61          in     ADP       4
13        been     AUX       4
120       very     ADV       4
48   governess    NOUN       3
46      friend    NOUN       3
125       with     ADP       2
5           an     DET       2
130      years    NOUN       2

In [17]:
pos_df_poscounts = pos_df.groupby(['pos_tag']).size().reset_index(name='counts').sort_values(by='counts', ascending=False  )
pos_df_poscounts.head(15)

   pos_tag  counts
6     NOUN      44
1      ADP      28
2      ADV      22
0      ADJ      19
12    VERB      19
5      DET      18
9     PRON      18
3      AUX      16
4    CCONJ      11
10   PROPN       8
8     PART       5
7      NUM       3
11   SCONJ       3

In [20]:
nouns= pos_df[pos_df['pos_tag'] == 'NOUN'][0:10]
nouns.head(15)

          token pos_tag
9          home    NOUN
12  disposition    NOUN
20    blessings    NOUN
22    existence    NOUN
28        years    NOUN
31        world    NOUN
36     distress    NOUN
38          vex    NOUN
47    daughters    NOUN
53       father    NOUN